#!/usr/bin/perl

use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;
use Digest::MD5 qw(md5_hex);
use LWP::UserAgent;
use HTTP::Request::Common;

my $whc = new Warehouse;
$whc->_hash_keeps();
my $ua = new LWP::UserAgent;

my %stats;

my %expect;
my %sawmanifestmd5;
my @manifest = $whc->list_manifests;
foreach (@manifest)
{
    my ($key, $name) = @$_;
    if ($key =~ /\+K([0-9a-f]{2})/)
    {
	++$stats{manifests} if $key =~ /^([0-9a-f]{32})\b/ && 1 == ++$sawmanifestmd5{$1};
	++$stats{manifestnames};
	my $m = new Warehouse::Manifest (whc => $whc, key => $key);
	$m->rewind;
	while (my $s = $m->subdir_next)
	{
	    foreach my $hash (split (" ", $s->as_string))
	    {
		next if $hash =~ /^\./;
		last if $hash !~ /^[0-9a-f]{32}/;
		my $expect = expecthowmany ($hash);
		$hash =~ s/\+[^\d\+][^\+]*//g;
		$expect{$hash} = $expect if $expect{$hash} < $expect;
	    }
	}
	foreach (split (",", $key))
	{
	    my $expect = expecthowmany ($_);
	    $expect{$_} = $expect if $expect{$_} < $expect;
	}
    }
}
$stats{blocksexpected} = scalar keys %expect;

my %got;
foreach my $keep_host_port (@{$whc->{keeps}})
{
    my $url = "http://".$keep_host_port."/index";
    my $req = HTTP::Request->new (GET => $url);
    my $r = $ua->request ($req);
    die "$url failed: ".$r->status_line unless $r->is_success;
    foreach (split ("\n", $r->content))
    {
	++$got{$_} if /\+/;
    }
    print STDERR ".";
}
print STDERR "\n";

my %md5size;
foreach (keys %got)
{
    /^([^\+]+).*\+(\d+)/ or die "$_ has no size hint";
    $md5size{$1} = $2;
    $stats{bytes} += $2;
    $stats{blocks} ++;
    $stats{diskbytes} += $2 * $got{$_};
    $stats{diskblocks} += $got{$_};
}

my %expectmd5;
map { $expectmd5{$1} = $expect{$_} if /^([0-9a-f]+)/ && $expectmd5{$1}<$expect{$_} } keys %expect;
delete $expectmd5{"d41d8cd98f00b204e9800998ecf8427e"};

my %gotmd5;
map { $gotmd5{$1} += $got{$_} if /^([0-9a-f]+)/ } keys %got;
delete $gotmd5{"d41d8cd98f00b204e9800998ecf8427e"};

foreach (keys %expectmd5)
{
    $stats{blocksmissing}++ unless $gotmd5{$_};
    if ($gotmd5{$_} > $expectmd5{$_})
    {
	$stats{blockstoomany}++;
	$stats{bytestoomany} += ($gotmd5{$_} - $expectmd5{$_}) * $md5size{$_};
    }
    elsif ($gotmd5{$_} < $expectmd5{$_})
    {
	$stats{blockstoofew}++;
	warn "$_ expect $expectmd5{$_} got $gotmd5{$_}\n";
    }
    $stats{"bytesexpected$expectmd5{$_}"} += $md5size{$_};
}

foreach (keys %gotmd5)
{
    if (!$expectmd5{$_})
    {
	$stats{blocksgarbage}++;
	$stats{bytesgarbage} += $md5size{$_} * $gotmd5{$_};
    }
}

map { print "$_ = $stats{$_}\n" } sort keys %stats;


sub expecthowmany
{
    my $hash = shift;
    my $expect = 0;
    if ($hash =~ /\+K([0-9a-f]{2})/)
    {
	for my $bit (0..7)
	{
	    if ((hex($1) >> $bit) & 1)
	    {
		++$expect;
	    }
	}
    }
    return $expect || 1;
}
