#!/usr/bin/perl

use Fcntl ':flock';

if (@ARGV != 2)
{
  die "usage: $0 {revision-number} {repository-url}";
}

maybe_install_revision (@ARGV);

sub maybe_install_revision
{
  my ($revision, $repos) = @_;
  my $revdir = "/usr/local/polony-tools/$revision";
  if (mkdir $revdir)
  {
    if (fork() == 0)
    {
      close(STDIN);
      chdir $revdir or die "$!";
      symlink ".", "install" or die "$!";
      open L, ">.log" or die "$!";
      open STDOUT, ">&L" or die "$!";
      open STDERR, ">&L" or die "$!";
      flock L, LOCK_EX;
      system (qw(svn export -r), $revision, $repos, "src")
	  == 0 or die "$?";
      open F, ">.fetched" or die "$!";
      system (qw(sh ./src/tests/autotests.sh))
	  == 0 or die "$?";
      open F, ">.installed" or die "$!";
      open F, ">.tested" or die "$!";
      close STDIN;
      close STDOUT;
      close L;
      exit 0;
    }
    wait;
    return 1 if ($? == 0);
    die "Installation failed";
  }
  else
  {
    return 1 if (-e "$revdir/.tested");
    sleep 5;
    open L, "<$revdir/.log" or die "$!";
    if (flock L, LOCK_SH)
    {
      close L;
      return 1 if (-e "$revdir/.tested");
    }
    die "Previous installation was abandoned";
  }
}
