#!/usr/bin/perl

use Warehouse::Keep;

open STDERR, ">&STDOUT";

$ENV{NODECRYPT} = 1;

my $dirs = [];
open (M, "/proc/mounts");
while (<M>) {
    push @$dirs, "$2/keep"
	if m/^(\/dev\/\S+|tmpfs) (\S+) /
	&& -d "$2/keep"
	&& $2 ne "/";
}
close M;

my $keepd = Warehouse::Keep->new (Directories => $dirs);

map { print "Using local directory $_\n" } @$dirs;
print "Listening at " . $keepd->url . "\n";

$keepd->run;
