static void taql_pack_uint64 (void * mem, size_t bit_offset, t_taql_uint64 v);
static void taql_pack_uint8 (void * mem, size_t bit_offset, t_taql_uint32 v);
static void taql_pack_int4 (void * mem, size_t bit_offset, t_taql_int32 v);
static void taql_pack_dfloat (void * mem, size_t bit_offset, t_taql_dfloat v);
static void taql_pack_sfloat (void * mem, size_t bit_offset, t_taql_sfloat v);
static void taql_pack_int32 (void * mem, size_t bit_offset, t_taql_int32 v);
static void taql_pack_int8 (void * mem, size_t bit_offset, t_taql_int32 v);
static void taql_pack_uint32 (void * mem, size_t bit_offset, t_taql_uint32 v);
static void taql_pack_uint4 (void * mem, size_t bit_offset, t_taql_uint32 v);
static void taql_pack_sym (void * mem, size_t bit_offset, t_taql_sym v);
static void taql_pack_int64 (void * mem, size_t bit_offset, t_taql_int64 v);
static t_taql_uint64 taql_unpack_uint64 (void * mem, size_t bit_offset);
static t_taql_uint32 taql_unpack_uint8 (void * mem, size_t bit_offset);
static t_taql_int32 taql_unpack_int4 (void * mem, size_t bit_offset);
static t_taql_dfloat taql_unpack_dfloat (void * mem, size_t bit_offset);
static t_taql_sfloat taql_unpack_sfloat (void * mem, size_t bit_offset);
static t_taql_int32 taql_unpack_int32 (void * mem, size_t bit_offset);
static t_taql_int32 taql_unpack_int8 (void * mem, size_t bit_offset);
static t_taql_uint32 taql_unpack_uint32 (void * mem, size_t bit_offset);
static t_taql_uint32 taql_unpack_uint4 (void * mem, size_t bit_offset);
static t_taql_sym taql_unpack_sym (void * mem, size_t bit_offset);
static t_taql_int64 taql_unpack_int64 (void * mem, size_t bit_offset);
extern const char * taql__type_tag_name (const char * file, size_t line, enum taql_type_tag t);
extern int taql__lex_typename (enum taql_type_tag * type, const char * s);
static int taql__bitsof (const char * file, size_t line, enum taql_type_tag t);
static int taql__eq (const char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql_box_uint64 (t_taql_uint64 v);
static t_taql_boxed taql_box_uint8 (t_taql_uint32 v);
static t_taql_boxed taql_box_int4 (t_taql_int32 v);
static t_taql_boxed taql_box_dfloat (t_taql_dfloat v);
static t_taql_boxed taql_box_sfloat (t_taql_sfloat v);
static t_taql_boxed taql_box_int32 (t_taql_int32 v);
static t_taql_boxed taql_box_int8 (t_taql_int32 v);
static t_taql_boxed taql_box_uint32 (t_taql_uint32 v);
static t_taql_boxed taql_box_uint4 (t_taql_uint32 v);
static t_taql_boxed taql_box_sym (t_taql_sym v);
static t_taql_boxed taql_box_int64 (t_taql_int64 v);
static t_taql_uint64 taql__unbox_uint64 (const char * file, size_t line, t_taql_boxed b);
static t_taql_uint32 taql__unbox_uint8 (const char * file, size_t line, t_taql_boxed b);
static t_taql_int32 taql__unbox_int4 (const char * file, size_t line, t_taql_boxed b);
static t_taql_dfloat taql__unbox_dfloat (const char * file, size_t line, t_taql_boxed b);
static t_taql_sfloat taql__unbox_sfloat (const char * file, size_t line, t_taql_boxed b);
static t_taql_int32 taql__unbox_int32 (const char * file, size_t line, t_taql_boxed b);
static t_taql_int32 taql__unbox_int8 (const char * file, size_t line, t_taql_boxed b);
static t_taql_uint32 taql__unbox_uint32 (const char * file, size_t line, t_taql_boxed b);
static t_taql_uint32 taql__unbox_uint4 (const char * file, size_t line, t_taql_boxed b);
static t_taql_sym taql__unbox_sym (const char * file, size_t line, t_taql_boxed b);
static t_taql_int64 taql__unbox_int64 (const char * file, size_t line, t_taql_boxed b);
static enum taql_type_tag taql_typeof (t_taql_boxed v);
static void taql__pack_boxed (const char * file, size_t line, void * mem, size_t bit_offset, enum taql_type_tag type, t_taql_boxed v);
static t_taql_boxed taql__unpack_boxed (const char * file, size_t line, void * mem, size_t bit_offset, enum taql_type_tag type);
static t_taql_boxed taql__cast_to_uint64 (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_uint8 (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_int4 (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_dfloat (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_sfloat (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_int32 (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_int8 (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_uint32 (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_uint4 (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_sym (const char * file, size_t line, t_taql_boxed b);
static t_taql_boxed taql__cast_to_int64 (const char * file, size_t line, t_taql_boxed b);
extern t_taql_boxed taql__cast_to (const char * file, size_t line, t_taql_boxed b, enum taql_type_tag type);
static t_taql_uint64 taql__asa_uint64 (const char * file, size_t line, t_taql_boxed b);
static t_taql_sfloat taql__asa_sfloat (const char * file, size_t line, t_taql_boxed b);
static t_taql_dfloat taql__asa_dfloat (const char * file, size_t line, t_taql_boxed b);
static t_taql_int32 taql__asa_int32 (const char * file, size_t line, t_taql_boxed b);
static t_taql_uint32 taql__asa_uint32 (const char * file, size_t line, t_taql_boxed b);
static t_taql_int64 taql__asa_int64 (const char * file, size_t line, t_taql_boxed b);
static t_taql_sym taql__asa_sym (const char * file, size_t line, t_taql_boxed b);
static void taql__binop_cast (const char * file, size_t line, t_taql_boxed * a, t_taql_boxed * b);
static t_taql_boxed taql__bor (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__bxor (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__mod (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__mul (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__div (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__add (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__band (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__sub (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__lor (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__land (char * file, size_t line, t_taql_boxed a, t_taql_boxed b);
static t_taql_boxed taql__neg (char * file, size_t line, t_taql_boxed a);
static t_taql_boxed taql__lnot (char * file, size_t line, t_taql_boxed a);
static t_taql_boxed taql__bnot (char * file, size_t line, t_taql_boxed a);
static t_taql_boxed taql__inc (char * file, size_t line, t_taql_boxed a);
static t_taql_boxed taql__dec (char * file, size_t line, t_taql_boxed a);
extern void taql__fmt_sym (const char * file, size_t line, char * buf, size_t bufsize, t_taql_sym v);
extern void taql__fmt (const char * file, size_t line, char * buf, size_t bufsize, t_taql_boxed b);


/* arch-tag: Thomas Lord Fri Oct 27 17:03:05 2006 (libtaql/g-prototypes.h)
 */


