#!/bin/sh

gpg --import --quiet --batch <<EOF >&2
$GPG_KEYS
EOF

# gpg --list-secret-keys | perl -ne 'print ",$1" if /<(.*?)>/' | sed 's/^,//'

cat >>$GNUPGHOME/gpg.conf <<EOF

compress-algo none
always-trust
EOF
