#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:read binary tuples (mers, read ids) and place against reference mers.
###MR_INPUT:manifest

$ENV{"KNOB_FUNCTION"} = "mrs-awz-place";
$ENV{"KNOB_OUTPUTNAME"} = "out.txt"; 

exec "mr-awz-stream" or die "exec mr-awz-stream: $!";
