#!/usr/bin/perl

###MR_INPUT:frames

use MetaMog;
use Compress::Zlib; 

if ($ENV{MR_LEVEL} == 0)
{
  # init
  $ENV{MR_INPUT} = $ENV{MR_INPUT0};
  open STDIN, "mrtask-framelist |" or die "Input pipe failed: $!";
  while (defined ($_ = <STDIN>))
  {
    chomp;
    print STDERR "+++mrjobstep 1 $_+++\n";
  }
  close STDIN or die "Input stream exited $?";
  print STDERR "+++mrjobstep 2 +++\n";
}

elsif ($ENV{MR_LEVEL} == 1)
{
  # map
  $ENV{PATH} .= ":/usr/local/polony-tools/$ENV{MR_REVISION}/src/align-call";

  my (@hybrid) = split (",", $ENV{KNOB_HYBRID});
  my (@baseorder) = split (",", $ENV{KNOB_BASEORDER});
  $ENV{HYBRIDDIRORDER} = "@hybrid";
  $ENV{DIRORDER} = "@baseorder";
  for (qw(FOCUSPIXELS ALIGNWINDOW OBJECTTHRESHOLD))
  {
    $ENV{$_} = $ENV{"KNOB_$_"};
  }

  #this should be in (numerical) frame order (!?!)
  open (STDIN, "mrtask-framekeys "
	. "| mrtask-streaminput --raw-images "
	. "| perl -S find_objects-register_raw_pipe.pl "
	. "| perl -S raw_to_reads.pl |")
      or die "Input pipe failed: $!";
  while (defined ($_ = <STDIN>))
  {
    print "$ENV{MR_INPUT} $_";
  }
  close STDIN or die "Input stream exited $?";
}

elsif ($ENV{MR_LEVEL} == 2)
{
  # reduce
  open STDIN, "mrtask-streaminputkeys | mrtask-streaminput |";
  
  binmode STDOUT; 
  my $gz = gzopen (\*STDOUT, "wb") 
    or die "Cannot open stdout: $gzerrno\n"; 
  
  while (defined ($_ = <STDIN>))
  {
    my ($dataset_id, $frame_id, $read, $object_id, $size) = split; 
    my $output = sprintf ("%05d-%05d-%05d %s\n", $frame_id, $object_id, $size, $read);
    $gz->gzwrite($output) or die "error writing: $gzerrno\n";      
  }
  close STDIN or die "Input stream exited $?";
  $gz->gzclose; 
  print STDERR "+++mrjobstep 3 $ENV{MR_OUTPUTKEY}+++\n";
}

elsif ($ENV{MR_LEVEL} == 3)
{
  my $m = MetaMog->new;
  $m->rename ($ENV{MR_INPUT}, "mrjob/$ENV{MR_JOB_ID}") or die $m->errstr;
  $m->delete_all ($ENV{MR_INPUT}, "mrjobstep/$ENV{MR_JOB_ID}/");
}
