#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:visit all subdirectories and place samples from files ending in .txt 
###MR_INPUT:manifest
###MR_KNOBS:PREFIXBITS=5
###MR_KNOBS:SUFFIXBITS=27 

use strict; 
use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;
use IO::Uncompress::Gunzip qw(gunzip $GunzipError);
use Digest::SHA qw(sha512);

my $manifestkey = $ENV{MR_INPUT0};

if ($ENV{MR_LEVEL} == 0) {
  $ENV{MR_INPUT} = $manifestkey; 
  for(0..(2**$ENV{KNOB_PREFIXBITS})-1) 
  { 
    print STDERR "+++mrjobstep 1 $_+++\n"; 
  }
  print STDERR "+++mrout d41d8cd98f00b204e9800998ecf8427e+++\n";
  exit 0;
}
elsif ($ENV{MR_LEVEL} == 1) {
  my $whc = new Warehouse
      (memcached_size_threshold => $ENV{KNOB_MEMCACHED_SIZE});
  
  my $manifest = new Warehouse::Manifest (whc => $whc,
					  key => $manifestkey);
  

  my @bp = ('a', 'c', 'g', 't'); 
 
  my $prefixbp; 
  for (my $i = 0; $i < $ENV{KNOB_PREFIXBITS}; $i+=2) {
    $prefixbp .= $bp[($ENV{MR_INPUT}>>$i)&3];     
  } 
  my $outstream = new Warehouse::Stream (whc => $whc);
  my $name = "./".$ENV{MR_INPUT}; 
  $outstream->name ($name);
  $outstream->clear;
  $outstream->write_start ("$prefixbp.txt"); 

  my $filename; 
  
  my @count; 
  
  vec (my $bitstring, 2**$ENV{KNOB_SUFFIXBITS}, 4) = 15;

  my $suffixmask = 2**$ENV{KNOB_SUFFIXBITS}-1; 
  
 
  while (my $instream = $manifest->subdir_next) {    
    while (my ($pos, $size, $filename) = $instream->file_next) {
      last if !defined $pos; 
      $instream->seek ($pos); 
      my $reads; 
      if ($filename =~ m/\.txt.gz$/){
	while (my $dataref = $instream->read_until ($pos + $size)) {
	  my $zblob .= $$dataref; 
	} 
	gunzip \$zblob => \$reads or die $GunzipError; 
      }
      elsif ($filename =~m/\.txt$/){
	while (my $dataref = $instream->read_until ($pos + $size)) {
	  $reads .= $$dataref; 
	} 	
      }
      else {
	next; 
      }
      while (/(.*?\n)/g) { 

	#mer0,mer1,mer2,mer3,read_id,mer0_ref,mer1_ref,mer2_ref,mer3_ref 
	#individual, chr, ploidy, pos0, pos1, pos2, pos3, orient 
	my @read = split " ", $1;  

      }   
      print STDERR "read $filename\n";     
    }
  }
  #for (my $i=0; $i<2**27; $i++) {
  #  $count[vec ($bitstring, $i, 2)]++;
  #}
  #$outstream->write_data ("@count\n");
  
  
  $outstream->write_finish; 
  
  my $fragkey = $whc->store_block ($outstream->as_string)
      or die "store_block failed: ".$whc->errstr;
  print STDERR "+++mrout ".$fragkey."+++\n";
  print STDERR $whc->iostats;
  
  exit 0;  
}

sub revc {
  my ($bp) = @_; 
 
  $bp =~ tr/acgtACGT/tgcaTGCA/;
  return reverse $bp; 
}
