#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:place 12+12bp reads on human genome
###MR_INPUT:manifest
###MR_KNOBS:REFERENCE=88f0fab736bdf704a559ae48ade5a423
###MR_KNOBS:STEPSPERNODE=1

use strict; 
use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;
use Safepipe;

my $src = "/usr/local/polony-tools/$ENV{MR_REVISION}/src";

# level 0:
#  read sample and reference manifests
#  queue jobstep(s) for each chromosome:
#   input = {sample range, chromosome}

my $manifestkey = $ENV{MR_INPUT0};

if ($ENV{MR_LEVEL} == 0)
{
  $ENV{MR_INPUT} = $manifestkey;
  for (1..22, 'X', 'Y', 'M')
  {
    print STDERR "+++mrjobstep 1 chr$_.fa+++\n";
  }
  print STDERR "+++mrout d41d8cd98f00b204e9800998ecf8427e+++\n";
}

elsif ($ENV{MR_LEVEL} == 1)
{
  my $wantsubdir = $ENV{MR_INPUT};

  my $pid;

  open REPORTREFERENCE, "+>", "/tmp/reference.dat";
  open REPORTSAMPLES, "+>", "/tmp/samples.dat";

  Safepipe::readfrom ("main::SAMPLES",
		      "mrs-fetch -h '$manifestkey' . 26mers.txt",
		      "perl $src/billy/26mers-to-24mers-dat.pl",
		      "complement-mers -m mer0 -M mer1 -n 12",
		      "tee -a /tmp/samples.dat")
      or die "samples pipe failed: $!";

#   Safepipe::readfrom ("main::REPORTSAMPLES",
# 		      "mrs-fetch -h '$manifestkey' . 26mers.txt",
# 		      "perl $src/billy/26mers-to-24mers-dat.pl",
# 		      "complement-mers -m mer0 -M mer1 -n 12")
#       or die "reportsamples pipe failed: $!";

  Safepipe::readfrom ("main::REFERENCE",
		      "mrs-fetch -h '$ENV{KNOB_REFERENCE}' . '$ENV{MR_INPUT}'",
		      "perl $src/madeleine/chr-to-dat.pl -n 12 >/tmp/reference.dat; cat /tmp/reference.dat")
      or die "reference pipe failed: $!";

#   Safepipe::readfrom ("main::REPORTREFERENCE",
# 		      "mrs-fetch -h '$ENV{KNOB_REFERENCE}' . '$ENV{MR_INPUT}'",
# 		      "perl $src/madeleine/chr-to-dat.pl -n 12")
#       or die "reportreference pipe failed: $!";

  my $s_fileno = fileno("SAMPLES");
  my $r_fileno = fileno("REFERENCE");
  my $rr_fileno = fileno("REPORTREFERENCE");
  my $rs_fileno = fileno("REPORTSAMPLES");
  Safepipe::readfrom ("main::PLACED",
		      ["main::REFERENCE", "all-mers -m mer0 -n 12 <&$r_fileno"],
		      ["main::SAMPLES", "mer-nfa --snps --all --m0 12 --gmin0 0 --gmax0 20 --m1 12 -r - -s \@$s_fileno -o -"],
		      ["main::REPORTREFERENCE", "main::REPORTSAMPLES", "place-report --two-inrecs-per-sample -n 12 -r \@$rr_fileno -s \@$rs_fileno -p -"],
		      "billy-grep",
		      "mrs-store './$ENV{MR_INPUT}' mer-nfa-report.dat")
      or die "mer-nfa pipe failed: $!";
  close "SAMPLES";
  close "REFERENCE";
  close "REPORTREFERENCE";
  close "REPORTSAMPLES";

  my @out = <PLACED>;
  close "PLACED";

  print STDERR "mr-billy: @out\n" if $ENV{KNOB_DEBUG};

  while (0 <= (my $pid = wait)) { die "child $pid exited $?" if $?; }

  open OUT, "|mrs-output" or die "mrs-output: $!";
  print OUT @out;
  close OUT or die "mrs-output: $!";
  exit 0;
}
