#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:visit all subdirectories and generate samples  
###MR_INPUT:manifest
###MR_KNOBS:PRE=1
###MR_KNOBS:SUF=21 
###MR_KNOBS:K=8
###MR_KNOBS:BP=3142044949
###MR_KNOBS:PLOIDY=2 
###MR_KNOBS:READ_LENGTH=18 
###MR_KNOBS:SEED=12345

use strict; 
use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;
use IO::Uncompress::Gunzip qw(gunzip $GunzipError);
use Digest::SHA qw(sha512);

my $manifestkey = $ENV{MR_INPUT0};

my $mer = $ENV{KNOB_K}; 
my $read_length = $ENV{KNOB_READ_LENGTH}; 

if ($ENV{MR_LEVEL} == 0)
{
  $ENV{MR_INPUT} = $manifestkey; 
  for(0..(2**$ENV{KNOB_PRE})-1) 
  { 
    print STDERR "+++mrjobstep 1 $_+++\n"; 
  }
  print STDERR "+++mrout d41d8cd98f00b204e9800998ecf8427e+++\n";
  exit 0;
}
elsif ($ENV{MR_LEVEL} == 1)
{
  my $whc = new Warehouse
      (memcached_size_threshold => $ENV{KNOB_MEMCACHED_SIZE});
  
  my $manifest = new Warehouse::Manifest (whc => $whc,
					  key => $manifestkey);
	
  my $outstream = new Warehouse::Stream (whc => $whc);
  my $name = "./".$ENV{MR_INPUT}; 
  $outstream->name ($name);
  $outstream->clear;
  $outstream->write_start ("reads.txt"); 

  #setup global variables for "awzprng" 
  $main::awzprngseed = $ENV{KNOB_SEED}.$name;
  $main::awzprngbits = 0; 
  $main::awzprngblocks = 0; 
  print STDERR "AWZPRNGSEED = $main::awzprngseed\n";
			
  my @reads; 

  for (my $i = 0; $i < (2**$ENV{KNOB_SUF}); $i++ ){
    $reads[$i] = (((awzprng(64)%
		    ($ENV{KNOB_PLOIDY}*$ENV{KNOB_BP}))<<28)|$i);
  }  
  @reads = sort {$a <=> $b} (@reads);
  
		
  my $bp = 0; 
  my $current_read = 0; 

  $manifest->rewind; #isn't this already done by "new" above? --AWZ

  while (my $instream = $manifest->subdir_next)
  {
    
    while (my ($pos, $size, $filename) = $instream->file_next)
    {
      last if !defined $pos; 
      $instream->seek ($pos); 
      my $reference; 
      if ($filename =~ m/hap|rand/) {
	print STDERR "ignoring $filename\n"; 
	next; 
      }
      elsif ($filename =~ m/\.fa$/i) 
      {
	my $read;
	my $valid_read; 
	my $overflow_ref; 
	while (my $dataref = $instream->read_until ($pos + $size))
	{
	  $reference = $$dataref; 
	  $reference =~ s/^>.*\n//;
	  $reference =~ s/\n//g;
      
	  #do some work
	  my $bp_start = $bp;
	  $bp += length ($reference); 
	  
	  my $rand_bits = 0; 
	  my $count = 0; 
	  my $bit; 
	  
	  my $current_position = 0; 
      
	  while ( $current_read < @reads) {
	  
	    my $small_gap1 = awzprng(1);  
	    my $small_gap2 = awzprng(1);
	    my $orient = awzprng(1); 
	    my $big_gap = awzprng(9); 
	    my $readmask = 2**$ENV{KNOB_SUF}-1; 
	    
	    $current_position = $reads[$current_read] >> 28; 
	    $current_read++; 
	    
	    if ( ($current_position+7+3+$small_gap1+7+$big_gap+250+7+3+$small_gap2+7) < $bp){
	      my $answer_key = sprintf 
		  (" %X %X %X %X %X %X", 
		   $reads[$current_read] & $readmask,  
		   $current_position, $orient, 
		   $small_gap1, $big_gap, $small_gap2); 
	      my @readstart;
	      push @readstart, $current_position-$bp_start;
	      push @readstart, $readstart[-1] + 7 + 3 + $small_gap1;
	      push @readstart, $readstart[-1] + 7 + 250 + $big_gap;
	      push @readstart, $readstart[-1] + 7 + 3 + $small_gap2;
	      my $read0 =
		  substr($reference, $readstart[0], 7).
		  substr($reference, $readstart[1], 7).
		  substr($reference, $readstart[2], 7).
		  substr($reference, $readstart[3], 7);
	      $outstream->write_data ($read0.$answer_key."\n");
	      $valid_read++; 
	      $read++; 
	    }
	    else {
	      last; 
	    }
	  }
#	  my $overflow = $bp-$current_position; 
#	  $bp -= $overflow; 
# 	  $overflow_ref = substr
#	      ($reference, $current_position-$bp_start, $overflow); 
	}
	warn ($valid_read."/".$read." in ".$filename." (".$bp.")\n");	
      }
 	

    }
  }
  $outstream->write_finish; 

  #report randomness consumed 
  print STDERR "used AWZPRNGBLOCKS = $main::awzprngblocks\n";
 
  my $fragkey = $whc->store_block ($outstream->as_string)
      or die "store_block failed: ".$whc->errstr;
  print STDERR "+++mrout ".$fragkey."+++\n";
  print STDERR $whc->iostats;
 
  exit 0;  
}

sub awzprng {
   my ($bits) = @_;  
   if ( $main::awzprngbits < $bits) {     
     $main::awzprngseed = sha512($main::awzprngseed); 
     $main::awzprngbits = 512; 
     $main::awzprngblocks++; 
    }
   my $rand = 0; 
   for (my $i = 0; $i < $bits; $i++) { 
     $rand = $rand<<1|vec($main::awzprngseed,512-$main::awzprngbits--,1);
   }
   return $rand; 
}
