#!/usr/bin/perl

use Warehouse;

if ($ENV{MR_LEVEL} == 0)
{
    for ($i=0; $i<4096; $i++) {
	printf STDERR "+++mrjobstep 1 %03x+++\n", $i;
    }
    print STDERR "+++mrout d41d8cd98f00b204e9800998ecf8427e+++\n";
    exit 0;
}

my $prefix = $ENV{MR_INPUT};
my $whc = new Warehouse;

open STDOUT, "| mrs-store . $prefix.txt | mrs-output";

my $keeps = $whc->{keeps};
foreach (@$keeps) {
    if ($self->{config}->{keeps_status}->{$_} !~ /^down/) {
	my $cmd = sprintf "timeout 20 wget -O- -q http://%s/index/%s", $_, $prefix;
	system $cmd;
    }
}
