#!/usr/bin/perl

###MR_INPUT:images

use MetaMog;

if ($ENV{MR_LEVEL} == 0)
{
  # init
  $ENV{MR_INPUT} = $ENV{MR_INPUT0};
  open STDIN, "mrtask-streaminputkeys |";
  while (defined ($_ = <STDIN>))
  {
    chomp;
    print STDERR "+++mrjobstep 1 $_+++\n"
	if /\.(raw|tiff?)(\.g?z)?$/i;
  }
  close STDIN or die "Input stream exited $?";
  print STDERR "+++mrjobstep 2 +++\n";
}

elsif ($ENV{MR_LEVEL} == 1)
{
  # map
  open STDIN, "mrtask-streaminputkeys | mrtask-streaminput --raw-images |";
  undef $/;
  my $data = <STDIN>;
  close STDIN or die "Input stream exited $?";

  print "# $ENV{MR_INPUT}\n";

  open OUT, "| levels -i -s";
  print OUT $data;
  close OUT or die "Output stream exited $?";

  open OUT, "| levels -s";
  print OUT $data;
  close OUT or die "Output stream exited $?";
}

elsif ($ENV{MR_LEVEL} == 2)
{
  # reduce
  open STDIN, "mrtask-streaminputkeys | mrtask-streaminput |";
  while (defined ($_ = <STDIN>))
  {
    print;
  }
  close STDIN or die "Input stream exited $?";
  print STDERR "+++mrjobstep 3 $ENV{MR_OUTPUTKEY}+++\n";
}

elsif ($ENV{MR_LEVEL} == 3)
{
  my $m = MetaMog->new;
  $m->rename ($ENV{MR_INPUT}, "mrjob/$ENV{MR_JOB_ID}") or die $m->errstr;
}
