#!/usr/bin/perl

###MR_DESCRIPTION:job -> list of ouput keys
###MR_INPUT:jobs

$ENV{MR_INPUT} = $ENV{MR_INPUT0};
open STDIN, "mrtask-streaminputkeys |" or die "Input pipe failed: $!";
print <STDIN>;
close STDIN or die "Input stream exited $?";
