#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:maq SNPfilter
###MR_INPUT:manifest
###MR_KNOBS:MAQ_DEB=715ba7d3755667609193c68cdb5dec04

use strict; 
use Warehouse;

$ENV{KNOB_MAQ_DEB} ||= "715ba7d3755667609193c68cdb5dec04";

my $whc = new Warehouse;

my $tmp = $ENV{MR_JOBSTEP_TMP};
chdir ($tmp) or die "chdir $tmp: $!";
mkdir "out" or die "mkdir out: $!";

fetch_to_file ($whc, $ENV{KNOB_MAQ_DEB}, "maq.deb");
system ("dpkg --extract maq.deb .")
    == 0 or die "dpkg exited $?";

system ("whget $ENV{MR_INPUT0}/ $tmp/")
    == 0 or die "whget $ENV{MR_INPUT0}/ $tmp/ exited $?";

system ("./usr/bin/maq.pl SNPfilter -q 40 -w 5 -N 2 -d 3 -D 256 -n 20 $ENV{KNOB_SNPFILTER_ARGS} ./cns.snp.txt >out/cns.final.snp.txt")
    == 0 or die "maq SNPfilter exited $?";

my $key = `whput out/`;
$key =~ s/^(.*? |)([0-9a-f]{32}\S*).*/$2/s
    or die "whput did not provide a manifest key";
print STDERR "+++mrout $key+++\n";
exit 0;

sub fetch_to_file
{
  my ($whc, $hash, $filename) = @_;
  my $dataref = $whc->fetch_block_ref ($hash) or die "fetch $hash: ".$whc->errstr;
  open F, ">", $filename or die "open $filename: $!";
  print F $$dataref or die "write $filename: $!";
  close F or die "close $filename: $!";
  return 1;
}
