#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:maq mapview
###MR_INPUT:manifest
###MR_KNOBS:MAQ_DEB=715ba7d3755667609193c68cdb5dec04

use strict; 
use Warehouse;
use Safepipe;

$ENV{KNOB_MAQ_DEB} ||= "715ba7d3755667609193c68cdb5dec04";

my $tmp = $ENV{MR_JOBSTEP_TMP};
chdir ($tmp) or die "chdir $tmp: $!";
mkdir "out" or die "mkdir out: $!";

my $whc = new Warehouse;

fetch_to_file ($whc, $ENV{KNOB_MAQ_DEB}, "maq.deb");
system ("dpkg --extract maq.deb .")
    == 0 or die "dpkg exited $?";

Safepipe::readfrom ("main::MAQ",
		    "whget $ENV{MR_INPUT0}/all.map -",
		    "./usr/bin/maq mapview -",
		    "whput --as-stream --use-filename=all.aln.txt -")
    or die "Safepipe failed: $!";
my $stream = <MAQ>;
close MAQ or die "Pipe failed: $!";

print STDERR "+++mrout $stream+++\n";
exit 0;

sub fetch_to_file
{
  my ($whc, $hash, $filename) = @_;
  my $dataref = $whc->fetch_block_ref ($hash) or die "fetch $hash: ".$whc->errstr;
  open F, ">", $filename or die "open $filename: $!";
  print F $$dataref or die "write $filename: $!";
  close F or die "close $filename: $!";
  return 1;
}
