#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:maq assemble
###MR_INPUT:manifest
###MR_KNOBS:MAQ_DEB=ec9aba3c23989d66f813589e2d4450db
###MR_KNOBS:REFERENCE=99259f4330907e84fe7253bd4e52dd3e
###MR_KNOBS:REFERENCEFILE=homo_sapiens.bfa
###MR_KNOBS:QMAX=60
###MR_KNOBS:QMIN=0
###MR_KNOBS:MISMAX=7

use strict; 
use Warehouse;
use Safepipe;

$ENV{KNOB_MAQ_DEB} ||= "ec9aba3c23989d66f813589e2d4450db";
$ENV{KNOB_REFERENCE} ||= "99259f4330907e84fe7253bd4e52dd3e";
$ENV{KNOB_REFERENCEFILE} ||= "homo_sapiens.bfa";
$ENV{KNOB_QMAX} ||= "60";
$ENV{KNOB_QMIN} ||= "0";
$ENV{KNOB_MISMAX} ||= "7";

my $tmp = $ENV{MR_JOBSTEP_TMP};
chdir ($tmp) or die "chdir $tmp: $!";
mkdir "out" or die "mkdir out: $!";

my $whc = new Warehouse;

fetch_to_file ($whc, $ENV{KNOB_MAQ_DEB}, "maq.deb");
system ("dpkg --extract maq.deb .")
    == 0 or die "dpkg exited $?";

system ("whget $ENV{KNOB_REFERENCE}/ $tmp/")
    == 0 or die "whget $ENV{KNOB_REFERENCE}/ $tmp/ exited $?";

Safepipe::readfrom ("main::MAQ",
		    "whget $ENV{MR_INPUT0}/all.map -",
		    "./usr/bin/maq assemble -N 2 -q $ENV{KNOB_QMIN} -Q $ENV{KNOB_QMAX} - $ENV{KNOB_REFERENCEFILE} -",
		    "whput --as-stream --use-filename=consensus.cns -")
    or die "Safepipe failed: $!";
my $stream = <MAQ>;
close MAQ or die "Pipe failed: $!";

print STDERR "+++mrout $stream+++\n";
exit 0;

sub fetch_to_file
{
  my ($whc, $hash, $filename) = @_;
  my $dataref = $whc->fetch_block_ref ($hash) or die "fetch $hash: ".$whc->errstr;
  open F, ">", $filename or die "open $filename: $!";
  print F $$dataref or die "write $filename: $!";
  close F or die "close $filename: $!";
  return 1;
}
