#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:collate output of mr-place, fix sample IDs
###MR_INPUT:manifest
###MR_KNOBS:ONE_FILE_PER_CHR=1

use strict; 
use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;

my $manifestkey = $ENV{MR_INPUT0};

if ($ENV{MR_LEVEL} == 0)
{
  $ENV{MR_INPUT} = $manifestkey;
  if ($ENV{KNOB_ONE_FILE_PER_CHR})
  {
    for (1..22, 'X', 'Y', 'M')
    {
      print STDERR "+++mrjobstep 1 chr$_.fa+++\n";
    }
    print STDERR "+++mrout d41d8cd98f00b204e9800998ecf8427e+++\n";
  }
  else
  {
    $ENV{MR_LEVEL} = 1;
  }
}

if ($ENV{MR_LEVEL} == 1)
{
  my $whc = new Warehouse;
  my $outstream = new Warehouse::Stream (whc => $whc);
  $outstream->clear;
  $outstream->name ($ENV{KNOB_ONE_FILE_PER_CHR} ? $ENV{MR_INPUT} : ".");
  $outstream->write_start ("mer-nfa-report.txt");
  my $manifest = new Warehouse::Manifest (whc => $whc,
					  key => $manifestkey);
  $manifest->rewind;
  while (my $instream = $manifest->subdir_next)
  {
    if ($instream->name =~ m,^\./(.+)-(\d+)$,
	&& (!$ENV{KNOB_ONE_FILE_PER_CHR} || $1 eq $ENV{MR_INPUT}))
    {
      my $chr = $1;
      my $sample_base = $2;
      while (my ($pos, $size, $filename) = $instream->file_next)
      {
	last if !defined $pos;
	$instream->seek ($pos);
	my $buf = "";
	while (my $dataref = $instream->read_until ($pos + $size))
	{
	  substr ($$dataref, 0, 0) = $buf;
	  my $cursor = 0;
	  while (1)
	  {
	    my $newline = index $$dataref, "\n", $cursor;
	    if ($newline < 0)
	    {
	      $buf = substr ($$dataref, $cursor);
	      last;
	    }
	    my @r = split (/ /, substr ($$dataref, $cursor, $newline-$cursor), 2);
	    $r[0] += $sample_base;
	    splice @r, 1, 0, $chr;
	    print "@r\n";
	    $cursor = $newline + 1;
	  }
	}
      }
    }
  }
  $outstream->write_finish;
  my $fragkey = $whc->store_block ($outstream->as_string)
      or die "store_block failed: ".$whc->errstr;
  print STDERR "+++mrout ".$fragkey."+++\n";
  exit 0;
}
