#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:collate output of mr-place
###MR_INPUT:manifest

use strict; 
use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;
use Safepipe;

my $manifestkey = $ENV{MR_INPUT0};
my $whc = new Warehouse;
my @subdirs;
my $m = new Warehouse::Manifest (whc => $whc,
				 key => $manifestkey);
$m->rewind;
while (my $s = $m->subdir_next)
{
  if ($s->name =~ /^(.*)-0$/)
  {
    push @subdirs, $1."-*";
  }
}

Safepipe::readfrom ("main::S",
		    "mrs-merge -h -t '$manifestkey' @subdirs",
		    "mrs-place-stats",
		    "mrs-store . place-stats.txt",
		    "mrs-output");
close "S" or die "close S: $!";
while (0 <= (my $pid = wait)) { die "child $pid exited $?" if $?; }
exit 0;
