#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:collate output of mr-place
###MR_INPUT:manifest
###MR_KNOBS:MERS_AND_GAPS=14,250-761,14
###MR_KNOBS:SMALLGAPMIN=3

use strict; 
use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;
use Safepipe;

my $manifestkey = $ENV{MR_INPUT0};

Safepipe::readfrom ("main::S",
		    "mrs-merge -h -t '$manifestkey'",
		    "mrs-place-stats",
		    "mrs-store . place-stats.txt",
		    "mrs-output");
close "S" or die "close S: $!";
while (0 <= (my $pid = wait)) { die "child $pid exited $?" if $?; }
exit 0;
