#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

###MR_DESCRIPTION:split unsorted BAM files into sorted bins
###MR_INPUT:manifest
###MR_KNOBS:SAM
###MR_KNOBS:REFERENCE
###MR_KNOBS:CHUNKSIZE

use strict; 
use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;
use Safepipe;
use Fcntl ':flock';
use POSIX qw(strftime);


my $tmp = $ENV{MR_JOBSTEP_TMP};

my $verbose = 1;
my $input_manifest_key = $ENV{MR_INPUT0} or die;
my $reference_manifest_key = $ENV{KNOB_REFERENCE};
my $sam_manifest_key = $ENV{KNOB_SAM} or die;
my $chunksize = $ENV{KNOB_CHUNKSIZE};
$chunksize = 1_000_000 if !defined $chunksize;
my $reffile = "$tmp/ref";

my $sam_path="$tmp/sam";

my $whc = new Warehouse;

my $index_path;
if (defined $reference_manifest_key) {
  $index_path = "$tmp/chrom.fa.fai";
  atomic_whget("$reference_manifest_key/chrom.fa.fai", $index_path);
}

if ($ENV{MR_LEVEL} == 0)
{
  my $m = new Warehouse::Manifest (whc => $whc, key => $ENV{MR_INPUT});
  $m->rewind;
  my $stream_index = -1;
  while (my $s = $m->subdir_next) {
    ++$stream_index;
    my $stream;
    while (my ($pos, $size, $filename) = $s->file_next)
    {
      last if !defined $pos;
      next if $filename !~ /^(.*)\.[bs]am$/;

      print STDERR "+++mrjobstep 1 $stream_index $pos:$size:$filename+++\n";
    }
  }

  print STDERR "+++mrout d41d8cd98f00b204e9800998ecf8427e+++\n";
  exit 0;
}
if ($ENV{MR_LEVEL} == 1)
{
  my ($want_stream_index, $file_list) = split (" ", $ENV{MR_INPUT}, 2);
  my $stream;

  my $m = new Warehouse::Manifest (whc => $whc, key => $ENV{MR_INPUT0});
  $m->rewind;
  my $stream_index = -1;
  while (my $s = $m->subdir_next) {
    ++$stream_index;
    next if $stream_index < $want_stream_index;
    chomp ($stream = $s->as_string);
    $stream =~ s/ \d+:\d+:.*/ $file_list/;
    last;
  }
  die "stream index $want_stream_index not found" if !defined $stream;

  my $dir ="$tmp/out";
  system "rm -rf $dir";
  mkdir $dir or die "mkdir $dir";
  chdir $dir or die "chdir $dir: $!";

  atomic_whget_tar("$sam_manifest_key/samtools.tgz", $sam_path);
  my $s = new Warehouse::Stream (whc => $whc, subdir => $stream);

  my $outpid = open STDOUT, "| mrs-output" or die "mrs-output: $! $?";

  my $streamname = $s->name;
  while (my ($pos, $size, $filename) = $s->file_next)
  {
    last if !defined $pos;
    $filename =~ s/\.([bs])am$//;
    my $samtools_view_s_flag = $1 eq "s" ? "-S" : "";
    $filename =~ s/[\'\"\s]//g;

    my $store_cmd;
    if ($chunksize > 0) {
      my $chunklines = 4 * $chunksize;
      $store_cmd = "mrs-split-store -z --lines=$chunklines --filesperstream=10 . \"$filename.{}.fastq.gz\"";
    } else {
      $filename =~ s/$/.fastq.gz/;
      $store_cmd = "gzip -9n | whput --as-stream --use-filename=\"$filename\" -";
    }
    my $index_args = defined ($index_path) ? "-t $index_path" : "";
    open WHPUT, "| bash -c 'set -o pipefail; exec $sam_path/samtools view $samtools_view_s_flag $index_args - | mrs-sam2fastq | $store_cmd'"
	or die "no fork";
    $s->seek ($pos);
    while (my $dataref = $s->read_until ($pos+$size)) {
      print WHPUT $$dataref;
    }
    close WHPUT or die "samtools view|mrs-sam2fastq|gzip|whput: error $! exit $?";
  }

  close STDOUT or die "mrs-output: error $! exit $?";
  exit 0;
}

sub whget {
  my ($source, $target) = @_;

  if (0 != system "whget '$source' '$target'")
  {
    die "whget exited $?";
  }
}

sub atomic_whget {
  my ($source, $target) = @_;

  if (open (L, "+>>", "$target.lock") &&
      flock (L, LOCK_EX) &&
      !-e ($target))
  {
    if (0 != system "whget '$source' '$target.tmp'")
    {
      system "rm -rf '$target.tmp'";
      close L;
      die "whget exited $?";
    }
    rename "$target.tmp", $target;
    system "rm -rf '$target.tmp'";
  }
  close L;
  die "Failed to whget $source -> $target" if !-e $target;
}

sub atomic_whget_tar {
  my ($source, $target) = @_;

  system "rm -rf '$target'";
  if (open (L, "+>>", "$target.lock") &&
      flock (L, LOCK_EX) )
  {
    if (0 != system "whget '$source' '$target.tgz.tmp'")
    {
      system "rm -rf '$target.tgz.tmp'";
      close L;
      die "whget exited $?";
    }
    rename "$target.tgz.tmp", "$target.tgz" or die "rename $target.tgz.tmp failed";
    mkdir "$target" or die "mkdir $target failed";
    system("tar -C $target -xzf $target.tgz") == 0 or die "tar -xz $target.tgz failed";
  }
  close L;
  die "Failed to whget $source -> $target" if !-e $target;
}

sub atomic_whget_dir {
  my ($source, $target) = @_;

  system "rm -rf '$target'";
  if (open (L, "+>>", "$target.lock") &&
      flock (L, LOCK_EX))
  {
    if (0 != system "whget -r '$source'/ '$target.tmp/'")
    {
      system "rm -rf '$target.tmp'";
      close L;
      die "whget exited $?";
    }
    rename "$target.tmp", $target;
    system "rm -rf '$target.tmp'";
  }
  close L;
  die "Failed to whget $source -> $target" if !-e $target;
}

sub emit_date {
  my $who = shift;
  my $now_string = strftime "%H:%M:%S", localtime;
  warn "$who @ $now_string\n";
}
