#!/usr/bin/perl

###MR_DESCRIPTION:gzipped files
###MR_INPUT:jobs

if ($ENV{MR_LEVEL} == 0)
{
  # init
  $ENV{MR_INPUT} = $ENV{MR_INPUT0};
  open STDIN, "mrtask-streaminputkeys |" or die "Input pipe failed: $!";
  while (defined ($_ = <STDIN>))
  {
    chomp;
    print STDERR "+++mrjobstep 1 $_+++\n";
  }
  close STDIN or die "Input stream exited $?";
}

elsif ($ENV{MR_LEVEL} == 1)
{
  # map
  open (STDIN, "mrtask-streaminputkeys "
	. "| mrtask-streaminput "
	. "| zcat "
	. "| md5sum |")
      or die "Input pipe failed: $!";
  while (defined ($_ = <STDIN>))
  {
    print "$ENV{MR_INPUT} $_";
  }
  close STDIN or die "Input stream exited $?";

}
