#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

# sort [args], but preserve order of taql headers

use strict;

my @sortargs = @ARGV;
@ARGV = ();

while (<>)
{
  if (/^\#/)
  {
    print;
  }
  else
  {
    $| = 1;
    open STDOUT, '|-', 'sort', @sortargs or die "sort: $!";
    print;
    while (<>)
    {
      print;
    }
    close STDOUT or die "sort: $!";
    die "sort exited $?" if wait != -1 && $?;
    last;
  }
}
exit 0;
