#!/usr/bin/perl

use strict;

while(<>)
{
    if (!/^\#/)
    {
	if ($ENV{KNOB_SKIPDEGENERATES})
	{
	    next if !/^[acgt ]{35} /i;
	}
	if ($ENV{KNOB_SKIPNOSNPS})
	{
	    next if /^\S+ \S+ \S+ \S+ \S+ [a-z ]{35} /;
	}
    }
    print;
}
