#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

my ($nmin, $nmax) = split (/-/, $ENV{KNOB_N});
$nmax ||= $nmin;

my ($mmin, $mmax) = split (/-/, $ENV{KNOB_M});
$mmax ||= $mmin;

open MEGABLAST, "<&STDIN";
close STDIN;

my $npipes = 0;
for my $m ($mmin..$mmax)
{
  for my $n ($nmin..$nmax)
  {
    open ("pipe$npipes", "|-") || do
	{
	  open MEGATRI, "-|", "../apps/awz/megatri.pl", "-n", $n, "-m", $m;
	  my %mismatch;
	  while (<MEGATRI>)
	  {
	    if (/(\S+)\}(\S+)/)
	    {
	      my ($xxx, $yyy) = ($1, $2);
	      my $x = substr $xxx, $m, 1;
	      my $y = substr $yyy, $m, 1;
	      ++$mismatch{$x.$y};
	    }
	  }
	  print STDERR map { "m=$m n=$n $_=$mismatch{$_}\n" } keys %mismatch
	      if $ENV{KNOB_DEBUG};
	  close MEGATRI;
	  print map { "m=$m n=$n $_=$mismatch{$_}\n" } keys %mismatch;
	  close STDOUT;
	  exit 0;
	};
    ++$npipes;
  }
}
close STDOUT;

while(<MEGABLAST>)
{
  for (my $p=0; $p<$npipes; $p++)
  {
    print { "pipe$p" } $_;
  }
}
close MEGABLAST;
