#!/usr/bin/perl -n

BEGIN {
    $main::targetlength = shift or die "usage: $0 targetlength";
}

next if /^\#/;
die "input format error" unless /^\@/;
my $bphead = $_;
my $bpdata = <>;
my $qhead = <>;
my $qdata = <>;
if ($bphead =~ m/^\@F=(\d+)/ && $1 & 0x10) {
    # if the read has been reversed in previous processing,
    # trim off the leftmost bases/transitions instead of rightmost
    for ($bpdata, $qdata) {
	s/(.*)(.{$targetlength})/$2/;
    }
}
if ($targetlength <= length($bpdata) - 1) {
    print ($bphead,
	   substr($bpdata, 0, $targetlength), "\n",
	   $qhead,
	   substr($qdata, 0, $targetlength), "\n");
}
