#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

use strict; 
use Warehouse;
use Warehouse::Manifest;
use Warehouse::Stream;

 
my $dump_N = $ENV{"KNOB_DUMP_READS"};
my $ref_key = $ENV{"KNOB_REFERENCE"}; 
my $prefix = $ENV{"MR_ID"}-1; 
my $place_ref = \&place0;
$place_ref = \&place1 if $ENV{"KNOB_VARIANT"};

print STDERR "PREFIX *** $prefix ***\n"; 

my $index; 
my $buf; 

if (2**26 != read(STDIN, $index, 2**26)) {
  die "failed to read 2**26 byte index\n";
}
my $count = vec ($index, 2**24-1, 32);  

if ($count*2 != read(STDIN, $buf, $count*2)) {
  die "failed to read $count reads\n"; 
}

#conceivably exits without consuming all input (eg. if malformed input.)
print STDERR "count = $count\n"; 


if ($dump_N) {
  dump_reads($dump_N);
}
else {
  place_reads (); 
  
}

sub dump_reads {
  my ($dump_N) = @_; 
  my %hash; 

  for (my $i = 0; $i < 2**24; $i++ ) {
    my $start = $i ? vec($index, $i-1, 32) : 0;
    my $len = vec ($index, $i, 32) - $start; 
    $hash{$len}++;
    
    if ($i % $dump_N == 0) {
      for (my $j = 0; $j < $len; $j+=3) {
	print STDOUT
	    vec($buf, $start+$j, 16)." ".
	    vec($buf, $start+$j+1, 16)." ". 
	    vec($buf, $start+$j+2, 16)." ";  
      }
      if ($len) {
	print STDOUT "*** $i\n";
      }
    }  
  } 
  print "\nFrequencies:\n";
  while ( my ($k, $v) = each %hash ) {  
    $k/=3;
    print "$v $k\n"; 
  }
}

sub place_reads {
 
  my $whc = new Warehouse
      (memcached_size_threshold => $ENV{KNOB_MEMCACHED_SIZE});  #needed? 
  
  my $manifest = new Warehouse::Manifest (whc => $whc,
					  key => $ref_key);

  $manifest->rewind; 

  print STDERR "!!! opened $ref_key for input... !!!\n";  
  
  while (my $instream = $manifest->subdir_next) {
    while (my ($pos, $size, $filename) = $instream->file_next) {
      last if !defined $pos; 
      $instream->seek ($pos); 
      my $reference; 
      while (my $dataref = $instream->read_until ($pos+$size)) {
	print STDERR place_ref->($data_ref)." ".length($$dataref)." "; 
      } 
      print "$filename\n"; 
    }  
  }
  print STDERR $whc->iostats; 
}

sub place0 {

  my ($dataref) = @_; 

  my $count; 
  for ($i = 0; $i < length ($$dataref)-1400; $i+=2){
    if ( vec($$dataref, $i+1, 8) == $prefix) {
      my $suffix = 
	  vec($$dataref, $i, 8) <<16 | 
	  vec($$dataref, $i+10, 8) << 8 | 
	  vec($$dataref, $i+9, 8); 

      my $start = $suffix ? vec($index, $suffix-1, 32) : 0;
      my $stop = vec ($index, $suffix, 32); 

      $count += ($stop - $start);
    }
  }  
  return $count; 
}

sub place1 {

  my ($dataref) = @_; 
 
  my $count; 
  for ($i = 0; $i < length ($$dataref); $i+=2){
    if ( vec($$dataref, $i+1, 16) == $prefix) {

    }	
  }
  return $count; 
}
