#!/usr/bin/perl

use colorspace;

print <<EOF
\@HD	VN:1.0 SO:unsorted
EOF
    ;

while (<>)
{
    chomp;
    chomp ($cs = <>);
    $cs =~ tr/0123456./ACGTNNNN/;
    s/^>//;
    my ($chr, $pos) = /,(\d+)_(-?\d+)/;
    if ($chr eq "23") { $chr = "chrX"; }
    elsif ($chr eq "24") { $chr = "chrY"; }
    elsif ($chr eq "25") { $chr = "chrM"; }
    else { $chr = "chr$chr"; }

    next if $cs =~ /[^ACGT0123]/i;
    $bp = cs2a ($cs);

    $flags = 0;
    if ($pos < 0) {
	$bp = reverse $bp;
	$bp =~ tr/ACGTacgt/TGCATGCA/;
	$pos = 3 - length($cs) - $pos;
	$flags = 16;
    }
    else {
	++$pos;
    }

    $quality = "I" x length($bp);

    print (join ("\t",
		 $_, $flags, $chr, $pos, 0, length($bp)."M", "*", 0, 0, $bp, $quality),
	   "\n");
}
