#!/usr/bin/perl

use Safepipe;

open IN, "<&STDIN";
Safepipe::readfrom("main::POP",
		   ["main::IN", "gzip -cdf"],
		   "perl -ne 'print if /^chr/'",
		   "cut -f1-4",
		   "perl -ne 's/[\t ]/-/g; print if !/[NX]\$/ && !/A-A|C-C|G-G|T-T/ && /-[ACGT]-/'",
		   "cut -f1-2 -d-",
		   "sort -u",
		   "sed -e 's/-/\t/'",
		   "sort -snk 2,2",
		   "sort -sk 1,1");
close STDIN;
close IN;
print while <POP>;
close POP or die "close pipe: $!";
while (0 <= (my $pid = wait)) { die "child $pid exited $?" if $?; }
