#!/usr/bin/perl

use English;

$OUTPUT_FIELD_SEPARATOR = "\t";
$OUTPUT_RECORD_SEPARATOR = "\n";

%alphabet = qw(A A C C G G T T R A/G Y C/T K G/T M A/C S C/G W A/T);
sub nt_expand
{
    return $alphabet{shift @_};
}

while (<>)
{
    @F = split "\t";
    next if $F[4]<20;		# quality cutoff
    next if $F[0]=~/\D/;	# NT_XXXX instead of chromosome number?
    for ($F[0])
    {
      s:23:X:;			# "chromosome 23" is X
      s:24:Y:;			# "chromosome 24" is Y
    }
    $alleles = nt_expand ($F[3]);
    next if !$alleles;
    print ("chr".$F[0],
	   ".",
	   "SNP",
	   $F[1],
	   $F[1],
	   $F[4],
	   "+",".",
	   "alleles $alleles;ref_allele $F[2];read_depth $F[7]");
}
