#!/usr/bin/perl

my %stat;
while (<>)
{
    ++$stat{total};
    ++$stat{placed} if !/^0/;
    ++$stat{unique} if /^U/;
    ++$stat{"mm$1"} if /^U.*(\d)$/;
}

print join "\t", map { "$_=$stat{$_}" } qw(total placed unique exact);
print "\n";
