#!/usr/bin/perl

use strict;

my %addslashes = qw(A A
		    C C
		    G G
		    T T
		    M A/C
		    R A/G
		    W A/T
		    S C/G
		    Y C/T
		    K G/T
		    V A/C/G
		    H A/C/T
		    D A/G/T
		    B C/G/T
		    N A/C/G/T
		    X A/C/G/T);

while (<>)
{
    chomp;
    my @in = split;
    next if $in[1] !~ /^\d+$/;
    my $bp = $addslashes{uc $in[3]};
    next if !$bp;
    next if $bp eq "A/C/G/T";
    print join ("\t",
		$in[0],
		"maq", "SNP",
		$in[1], $in[1],
		".", "+", ".",
		"alleles $bp;ref_allele $in[2];read_depth $in[5]");
    print "\n";
}
