#!/usr/bin/perl

while (<>)
{
    chomp;
    my @a = split;
    if ($a[2] eq "R")
    {
	# fix intra-exon coordinate (distance from start in F direction)
	$a[3] = $a[1] - $a[3] - 1;

	# complement bases
	for(4,5)
	{
	    $a[$_]=~tr/ACGT/TGCA/;
	}
    }

    # fix intra-exon coordinate (might be negative or >= exon length
    # if alignment crosses date line)

    $a[3] = $a[3] % $a[1];
    $_ = join("\t",@a);
    print;
    print "\n";
}
