#!/usr/bin/perl
# -*- mode: perl; perl-indent-level: 2; -*-

use strict; 
use Warehouse;
my $whc = new Warehouse;

$ENV{KNOB_MAQ_DEB} ||= "715ba7d3755667609193c68cdb5dec04";

my $tmp = $ENV{MR_JOBSTEP_TMP};
chdir ($tmp) or die "chdir $tmp: $!";

fetch_to_file ($whc, $ENV{KNOB_MAQ_DEB}, "maq.deb");
system ("dpkg --extract maq.deb .")
    == 0 or die "dpkg exited $?";

my $maqprogram = "./usr/bin/maq";
if ($ARGV[0] =~ m{^/})
{
  $maqprogram = ".".$ARGV[0];
  shift @ARGV;
}

system ($maqprogram, @ARGV)
    == 0 or die "\`$maqprogram @ARGV\` exited $?";
exit 0;

sub fetch_to_file
{
  my ($whc, $hash, $filename) = @_;
  my $dataref = $whc->fetch_block_ref ($hash) or die "fetch $hash: ".$whc->errstr;
  open F, ">", $filename or die "open $filename: $!";
  print F $$dataref or die "write $filename: $!";
  close F or die "close $filename: $!";
  return 1;
}
