#!/usr/bin/perl

use strict;

my $merfieldsize;

while(<>)
{
    if (!/^\#/)
    {
	if (!defined $merfieldsize)
	{
	    if (/^([a-z ]+) \d/i)
	    {
		$merfieldsize = length $1;
	    }
	    else
	    {
		die "$0: Can't determine merfieldsize\n";
	    }
	}
	if ($ENV{KNOB_SKIPDEGENERATES})
	{
	    next if !/^[acgt ]{$merfieldsize} /i;
	}
	if ($ENV{KNOB_SKIPNOSNPS})
	{
	    next if /^\S+ \S+ \S+ \S+ \S+ [a-z ]{$merfieldsize} /;
	}
    }
    print;
}
