#!/usr/bin/perl

# mrtaskmanager: run a map or reduce function on one input.

use strict;
use MogileFS::Client;

$ENV{PATH} .= ":/usr/local/polony-tools/$ENV{MR_REVISION}/bin";
$ENV{PATH} .= ":/usr/local/polony-tools/$ENV{MR_REVISION}/src/mapreduce";
$ENV{PERLLIB} .= ":/usr/local/polony-tools/$ENV{MR_REVISION}/src/warehouse/lib:/usr/local/polony-tools/$ENV{MR_REVISION}/src/mapreduce";

foreach (split ("\n", $ENV{MR_KNOBS}))
{
  my ($k, $v) = split ("=", $_, 2);
  $ENV{"KNOB_$k"} = $v;
}

open STDOUT, ">/dev/null";
exec "mr-$ENV{MR_FUNCTION}";
die "mr-$ENV{MR_FUNCTION}: $!";
